name: test
on: [push, pull_request]
jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [15, 14, 12, 10, 8]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.node }}-${{ matrix.os }}-build-${{ hashFiles('package.json') }}
      - name: Build
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Test
        run: npm run test:ci
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Build
        run: npm install
      - name: Coverage
        run: npm run test:cov
      - name: Coveralls
        run: cat ./coverage/lcov.info | node_modules/.bin/coveralls
